title: Tailored by Tony
email: ymsimei@gmail.com
url: "http://tailoredbytony.com"
twitter_username: ymsimei
github_username:  ymsimei

# Build settings
markdown: kramdown
collections:
  projects:
    output: true
  persepectives:
    output: true
include: ['_pages']
